多加一个维度

In [14]:
from pylab import *
a = array([[1,2],[3,4]])
a = a[:,:,newaxis]
concatenate((a,a),axis = 2)


array([[[1, 1],
        [2, 2]],

       [[3, 3],
        [4, 4]]])

矩阵乘法

In [22]:
from pylab import *
a = array([[1,2],[3,4]])
b = np.zeros(a.shape)
b

array([[ 0.,  0.],
       [ 0.,  0.]])

In [24]:
from pylab import *
a = array([[1,2],[3,4]])
a = a[:,:,newaxis]
b = np.zeros(a.shape)
s1 = concatenate((a,a),axis = 2)
s2 = concatenate((b,b),axis = 2)
s1*s2

array([[[ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.]]])

查找

In [25]:
a = [1,2,3]
1 in a

True

In [31]:
from pylab import *
d = {}
d[1] = 33
d[0] = 35
print d
np.save("dic.npy",d)
c = np.load("dic.npy")
print c
print range(0,10)

{0: 35, 1: 33}
{0: 35, 1: 33}
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


存字典